USE GerenciamentoEscolar;
GO

DROP TABLE GES.Aluno;
DROP TABLE GES.PessoaFisica;

CREATE TABLE GES.PessoaFisica(
	Id INT IDENTITY NOT NULL,
	EntityId UNIQUEIDENTIFIER NOT NULL,
	DataCriacao DATETIME NOT NULL,
	Nome VARCHAR(200) NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	NomeSocial VARCHAR(200) NULL,
	Sexo CHAR(1) NOT NULL,
	DataNascimento DATETIME NOT NULL
)
GO
ALTER TABLE GES.PessoaFisica ADD CONSTRAINT PK_PessoaFisica PRIMARY KEY (Id)
GO
ALTER TABLE GES.PessoaFisica ADD CONSTRAINT UC_PessoaFisica_Cpf UNIQUE(Cpf);
GO

CREATE TABLE GES.Aluno(
	Id INT IDENTITY NOT NULL,
	EntityId UNIQUEIDENTIFIER NOT NULL,
	DataCriacao DATETIME NOT NULL,
	PessoaFisicaId INT NOT NULL,
	Matricula INT NOT NULL
)
GO
ALTER TABLE GES.Aluno ADD CONSTRAINT PK_Aluno PRIMARY KEY (Id)
GO
ALTER TABLE GES.Aluno ADD CONSTRAINT UC_Aluno_Matricula UNIQUE(Matricula);
GO
ALTER TABLE GES.Aluno ADD CONSTRAINT FK_Aluno_PessoaFisica FOREIGN KEY (PessoaFisicaId) REFERENCES GES.PessoaFisica(Id)
GO