USE Escola;
GO

DROP TABLE PFIS.PessoaFisica;

CREATE TABLE PFIS.PessoaFisica(
	Id INT IDENTITY NOT NULL,
	EntityId UNIQUEIDENTIFIER NOT NULL,
	DataCriacao DATETIME NOT NULL,
	Nome VARCHAR(200) NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	NomeSocial VARCHAR(200) NULL,
	Sexo CHAR(1) NOT NULL,
	DataNascimento DATETIME NOT NULL
)
GO
ALTER TABLE PFIS.PessoaFisica ADD CONSTRAINT PK_PessoaFisica PRIMARY KEY (Id)
GO
ALTER TABLE PFIS.PessoaFisica ADD CONSTRAINT UC_PessoaFisica_Cpf UNIQUE(Cpf);
GO